services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.12-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./config/clickhouse/users.d:/etc/clickhouse-server/users.d
    environment:
      CLICKHOUSE_DB: sbom
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
